server:
  port: 8082
  servlet:
    context-path: '/ead-course/'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_course
    username: rdgr777
    password: 995647
    jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSqlDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql:true
ead:
  api:
    url:
      user: 'http://localhost:8083/ead-authuser'

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    com.ead: DEBUG
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO